### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by miketwo**
Fixes a bunch of tests, but not all of them.

Not sure where you're going with `apply_effect`. ~~And not sure what the `None` errors are yet.~~

### CODE REVIEW

**Comment by vesper-arch** [comment]
oh my god I just looked at the `apply_effect` function and it inflicted mental damage on me

**Comment by vesper-arch** [comment]
Also for some reason the tests are all failing because the imports are failing

**Comment by miketwo** [comment]
I've got 2 tests that do like a "run through everything." One is `test_all_attack_cards_with_all_relics`, the other is `test_most_enemies_default_move`.

Each one only gets a little ways in before crashing:

    Playing card 5 of 47 - Havoc
    F

and 

    --->Testing: GremlinNob (Enemy #9 of 23)
    Bellow
    F


These tests may not be valid, depending on how you want combat to work, but I would suggest having a couple tests that are like this -- that run through a lot of cards or enemies or combinations.

**Comment by vesper-arch** [comment]
I think I have an idea of what is going on.

Havoc is an *interesting* card because it plays the top card of the player's draw pile and has to dynamically change the way it is called depending on its type. Probably some funny stuff happening there.

Gremlin Nob is an elite with a special buff called Enrage that I don't think I coded in so it is most likely crashing there.

**Comment by miketwo** [comment]
Havoc is playing a Corruption card, which then fails.

**Comment by vesper-arch** [comment]
Looks like just another error cause by the effects not existing

**Comment by miketwo** [comment]
Do you know the difference between these?

`(card for card in origin.hand if card.upgradeable is True and card.upgraded is False)`

`[card for card in origin.hand if card.upgradeable is True and card.upgraded is False]`

**Comment by vesper-arch** [comment]
ugh my ide isnt working

**Comment by vesper-arch** [comment]
Yup! Had to learn it the hard way lmao. First one is uhhh i forgot the exact word but not a tuple for sure.

**Comment by vesper-arch** [comment]
Is there a way i can help with working on this? It isn't on a branch on this repo so I dont know how to checkout or push to it

**Comment by miketwo** [comment]
Go ahead and approve/merge. Then you can start your own branch and make changes. Remember to keep it small and focused.

**Review by vesper-arch — APPROVED** [review]

**Pull request merged**
