### PR TITLE
E2E Test

### PR DESCRIPTION
**Pull request by miketwo**
I made a test that plays the game using mostly random inputs and I made it so that it runs the test 10 times. It's exposing _lots_ of bugs. 

I fixed one of the harder ones with the message bus -- it would act weird if a nested `publish()` was called. 

The other problems we'll have to work through together. If you have VSCode set up to run tests, it'll look like this:

image

### CODE REVIEW

**Comment by vesper-arch** [comment]
I do not have vscode set up. There might be some kind of tool that does something similar (I run the test in the terminal currently)

**Comment by vesper-arch** [comment]
I'll try and get some work done on this once I get out of school

**Comment by miketwo** [comment]
Chiseling away.

Did you want `self.buffs` to be a list of Effects? It looks like it was originally a dict, and still gets set to be a dict by a bunch of Enemy's `powers={...}` in their init.

A list makes more sense, because ordering can be preserved, but you'll have to handle duplicates manually.

**Comment by vesper-arch** [comment]
Yeah a list is what the new system will require since the previous one was a giant dictionary of every possible buff/debuff the player or enemy could have and all of them were set to 0 or false by default. Struggling with the new implementation though.

**Comment by miketwo** [comment]
Ok, I'll see what I can do. But if it's not understandable, we can always go back. This is a pet project -- it doesn't have to be coded perfectly. :-p

**Comment by miketwo** [comment]
The main issue here is that `BEFORE_ATTACK` is published from two places -- the player's `attack()` method and the enemy's `attack()` method, and they don't pass the same thing. For the player it passes the card object, who's damage can be modified before being used. But for the enemy it just passes the `dmg` and `target.block` -- basic integers which can't be modified by the function that's receiving them. In Python, passed objects can be modified, but basic types (like ints, floats, and strings) can't.

### Example

```python
def modify_value(value):
  value += 10

my_value = 5
print(f"Value Before: {my_value}")
modify_value(my_value)
print(f"Value After: {my_value}")

#--------------------------------------------
def modify_obj(obj):
  obj.value += 10

class MyObj:
  def __init__(self, value):
    self.value = value

my_obj = MyObj(5)
print(f"Object.Value Before: {my_obj.value}")
modify_obj(my_obj)
print(f"Object.Value After: {my_obj.value}")
```

If you run this, you'll get:

```text
Value Before: 5
Value After: 5
Object.Value Before: 5
Object.Value After: 15
```

Showing that the object can be modified but the integer can't. 

### Solution
So because of that, if you want something (like damage or block or health) to be modified, it has to be passed inside an object. That's why the player attack (using a card object) works but the enemy attack doesn't. 
To fix this, we'll want to make both `publish()` methods publish the same thing -- the attacker, the target, and a modifiable object representing the damage of the attack. 

Then, on the receiving end, we just need to do two things:
- "Is the message for me?" (i.e. If my buff/debuff effect is for attackers, make sure the attacker matches. If it's for defenders, make sure the target matches)
- "Adjust the damage" (depending on whether I'm a buff or debuff, and whether I'm on the attacker or defender, adjust the attack damage accordingly). 

I'll take a first crack at it.

**Comment by miketwo** [comment]
Slow and steady. On the bright side, it looks like 2 out of the 10 end-to-end tests didn't crash. 👍

**Comment by miketwo** [comment]
Sometimes the tests pass, sometimes they don't. I think we still have a problem with randomness. But I got it to mostly work.

**Review by vesper-arch — APPROVED** [review]

**Pull request merged**
